/*
    - METODOS ESTÁTICOS: SÃO METODOS QUE PODEM SER ACESSADOS SEM PRECISAR INSTANCIAR A SUA CLASSE
    - NÃO É POSSIVEL UTILIZAR O METODO ESTATICO RECEBENDO PARAMETRO DO CONSTRUTOR, POIS O CONSTRUTOR SÓ 
      FUCIONA QUANDO INSTANCIAMOS A CLASSE. NESSE CASO É MELHOR RECEBER POR PARAMETRO DE FUNÇÃO
*/

class User{
   static showMessage(){
        console.log("Essa é uma mensagem");
    }
}

const user = new User()
//user.showMessage()

User.showMessage() //SE NA CLASSE NÃO TIVESSE COMO static EU NÃO PODERIA UTILIZAR ELES